-- Світова карта (l2dop map.php)
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "worldX" INTEGER NOT NULL DEFAULT 83400;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "worldY" INTEGER NOT NULL DEFAULT 147943;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "targetX" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "targetY" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "moveStartAt" TIMESTAMP(3);
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "moveFromX" INTEGER NOT NULL DEFAULT 83400;
ALTER TABLE "Character" ADD COLUMN IF NOT EXISTS "moveFromY" INTEGER NOT NULL DEFAULT 147943;
